# Generated by Django 5.0.2 on 2025-03-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_add_initial_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoybeanMeal',
            new_name='SoybeanMealPrices',
        ),
    ]
